### PR TITLE
Ws adapter v2

### PR DESCRIPTION
**Pull request by splash5**
Supporting ws adapter v2 for HW4.
Also add more cart info and showing up progress bar when reading ROM
[ws_adapter_v2.zip](https://github.com/sanni/cartreader/files/8146787/ws_adapter_v2.zip)

### CODE REVIEW

**Comment by Bandmo** [comment]
What are the HW pads for?

**Comment by sanni** [comment]
Also remember that every PCB that goes into the SNES/NES or N64 slot will have to be ordered with 1.2mm thickness instead of the default 1.6mm or else it will not fit into the SNES slot.

**Comment by Bandmo** [comment]
Well shoot… I hope oshpark has them in the correct size. I didn’t see an option to change the thickness, only the amount of layers. I’ll check it out when they arrive. Thanks again!

- Brendon

**Comment by sanni** [comment]
Oshpark only does 1.6mm. If you can try to cancel the order. 
If the PCB is already in production you can still try it out but it will be a pretty tight fit into the SNES slot.

**Comment by Bandmo** [comment]
Done. Thanks. What about beveling?

- Brendon

**Comment by sanni** [comment]
Yes beveling is recommended for WS adapter.

**Comment by Bandmo** [comment]
I thought I canceled the order, but they showed up anyways. I tried it out, and it is a tight fit, but works. When I tried to order new pcbs through jlcpcb, the pcb had to meet a minimum size requirement in order to be beveled. I might just build a 2nd snes adaptor, and keep it as my wonderswan adaptor so I don't jack up the pins. Do you have a suggestion for another place to order the pcbs that will bevel? Thanks!

**Comment by splash5** [comment]
Hi, I recently got same problem when ordering from JLCPCB. You can try using PCBWay which they accept borad size smaller than 50mmx50mm to be beveled.

**Comment by PsyK0p4T** [comment]
I know this discussion is quite old now but @splash5 can you confirm me that your v2 adapter doesn't need the two capacitors which were on the v1 ?
Also, selecting the hw4 bridge should be fine with hw5 too right ?

I haven't builded it yet, just making a shopping-list various pieces before starting.

**Comment by breyell** [comment]
@PsyK0p4T Just assembled one. Can confirm HW4 jumper works for HW5.

**Comment by splash5** [comment]
@PsyK0p4T Yes V2 doesn't need that two capacitors. On V1 it's just an optional (everyone just installed them anyway).
And solder jumper HW4 means HW4 or later hardware revision (if wiring not change).

**Comment by PsyK0p4T** [comment]
Excellent, thank you guys for that reports :)
I'll maybe try to build on with a switch on the pcb, to make it compatible with every hardware version

**Comment by nsx0r** [comment]
This adapter works perfectly, thank you

ws1
ws2
ws3

**Pull request merged**
