### PR TITLE
Update nes.txt

### PR DESCRIPTION
**Pull request by fakkuyuu**
Fix wrong crc32
Added another version of Rockman 4
Added another version of Dragon Ball Z - Kyoushuu! Saiya Jin

### CODE REVIEW

**Comment by PsyK0p4T** [comment]
@fakkuyuu are you using discord ? if so, please contact me there. I would be interested by more info (pics, pcb...) for these new revisions of Rockman 4 and Dragon ball :)

**Comment by fakkuyuu** [comment]
I don't use Discord. I took pictures, but I don't want to take it apart.
IMG_20230410_184221
IMG_20230410_184231
IMG_20230410_184257
38-5dfcdb7a-8c5d-4c2d-9c40-251ecb1f89e1.jpg)

**Comment by PsyK0p4T** [comment]
Thanks a lot mate :)
Can you eventually make a delta patch for Dragon Ball Z, from the v0 rom to your v1 ? 
So we can rebuild it from our side. Looks like this version was unknown until now.

**Comment by fakkuyuu** [comment]
sorry i don't have v0

**Comment by PsyK0p4T** [comment]
Ok. So we can try something to generate a patch :

- download rdiff : https://github.com/librsync/librsync/files/10899495/librsync-win64-2.3.4-bin-with-popt.zip
- download this .sig file [DBZ.nes.sig.zip](https://github.com/sanni/cartreader/files/11200688/DBZ.nes.sig.zip)
- Once extracted, run the command line :
`rdiff delta "Dragon Ball Z - Kyoushuu! Saiya Jin (Japan).nes.sig" "Dragon Ball Z - Kyoushuu! Saiya Jin (Japan) (Rev 1).nes" rev0_to_rev1.delta
`
- and post here the rev0_to_rev1.delta file :)

**Comment by fakkuyuu** [comment]
I can't judge whether the method of passing the ROM data itself is legal in such a way, so I won't do it.
ROM Checker V1 54 2023_04_12 9_46_42

**Comment by PsyK0p4T** [comment]
Well, this method is often used to share just a few isolated bits, instead of a partial / complete ROM which would be illegal.
After 33 years, a delta file of a few random bytes should be safe ^^
Thanks for your screenshot anyway :)

**Comment by mariomadproductions** [comment]
Seems like something in the PRG ROM changed in Rev 1.

**Comment by Ancyker** [comment]
@fakkuyuu are you willing to sell it?

**Comment by splash5** [comment]
The only thing I curious about is first/last CRC32 of "Suikoden - Tenmei no Chikai (Japan)".
I have two of them and both gave me the same first/last CRC32 "0A9725FE", not the value "7F17649B" which @fakkuyuu updated.

@fakkuyuu  can you post the log about dumping "Suikoden - Tenmei no Chikai (Japan)"?

**Comment by fakkuyuu** [comment]
> @fakkuyuu are you willing to sell it?
I have no plans to sell it. However, this title is available in large quantities and is cheap, so if you get your hands on this version, I will give it to you. I don't think it's that rare software.




> splash5
OSCR HW3 V12.1

[+] Add-ons

[+] 80s Consoles

[+] NES/Famicom


Searching database
for 7F17649B...

CRC not found in database
Using manual selection

Printing PRG at 32768
4c e0 e0 20 24 e4 fc ff 61 64 61 e9 39 ee 06 40 
2b 6f 3b 6a e9 39 ee 06 0b d0 2b 0b 8b 20 c6 d7 
11 e0 8a b8 79 8c 04 60 bc 72 2a 3a 8e 04 60 8e 
04 a0 8e f7 00 62 e9 d6 f2 0a cf 20 24 e4 00 00 
0c a8 8d 79 0c d5 00 00 07 00 63 e0 5a e0 64 e0 
6a e0 70 e0 70 e0 76 e0 70 e0 8e e1 00 61 62 e9 
39 ee 06 cf 8e ee 00 d6 5d e0 8e e9 00 d6 5d e0 
8e e0 00 d6 5d e0 8e ec 00 d6 5d e0 20 24 e4 fc 
ff 8a 31 72 2a 47 2b 0a d3 8c ff 00 c1 d8 92 e0 
41 cf 0a d0 2a 0b d1 2b 0b d7 87 e0 40 cf 20 24 
e4 00 00 ac 7c e0 d8 ad e0 40 d6 ae e0 41 cf 20 
24 e4 ff ff a5 f6 71 53 c6 d8 c3 e0 a5 f6 71 7c 
d6 c6 e0 a5 f6 71 8f fd a2 ff ff a0 ff ff 53 b8 
73 b3 8d 1a e9 39 ee 04 61 8d 1b e9 39 ee 04 cf 
20 24 e4 00 00 ac 03 e0 66 e9 3b e0 02 64 e9 3b 
e0 02 ac af e0 a4 fd 71 d7 00 e1 61 e9 3b e0 02 
a5 fa 71 53 c1 d8 0d e1 60 e9 3b e0 02 a5 fa 71 
53 c0 d8 27 e1 ac 9e e0 d8 22 e1 40 a9 fa 71 d6 
e5 e0 63 e9 3b e0 02 a5 fa 71 55 c0 d8 f5 e0 d6 
1b e1 d6 f5 e0 d6 e5 e0 cf 20 24 e4 00 00 0e d7 
45 e1 89 ff cf 0e b7 26 b7 14 0d b7 26 b7 14 0c 
b7 26 b7 15 b7 01 b7 15 b7 02 b7 27 cf 20 24 e4 
00 00 3c 3e 0c b0 1d bb b3 e9 9f f2 04 b1 cf 20 
24 e4 00 00 3d 0c b0 b3 e9 9f f2 04 b3 0c b4 b3 
b0 bc b1 cf 20 24 e4 fe ff 8d 64 3d 0c b0 b3 e9 
39 e1 06 2b 3b 0c b4 b3 b0 bc b1 0b cf 20 24 e4 
00 00 0c d7 ad e1 0d d7 ad e1 89 32 cf 8d 63 61 
0c 1d bb b3 8d 64 3c e9 39 e1 06 b3 e9 a3 f2 04 
b3 e9 9f f2 04 cf 20 24 e4 fe ff 0d d7 d5 e1 0f 
d7 d5 e1 40 cf 0f b7 26 b7 14 0d b7 26 b7 15 b7 
03 b7 14 0f b7 26 b7 14 0e b7 26 b7 15 b7 01 b7 
14 0d b7 26 b7 14 0c b7 26 b7 15 b7 01 b7 15 b7 

Printing PRG at 57344
4c e0 e0 20 24 e4 fc ff 61 64 61 e9 39 ee 06 40 
2b 6f 3b 6a e9 39 ee 06 0b d0 2b 0b 8b 20 c6 d7 
11 e0 8a b8 79 8c 04 60 bc 72 2a 3a 8e 04 60 8e 
04 a0 8e f7 00 62 e9 d6 f2 0a cf 20 24 e4 00 00 
0c a8 8d 79 0c d5 00 00 07 00 63 e0 5a e0 64 e0 
6a e0 70 e0 70 e0 76 e0 70 e0 8e e1 00 61 62 e9 
39 ee 06 cf 8e ee 00 d6 5d e0 8e e9 00 d6 5d e0 
8e e0 00 d6 5d e0 8e ec 00 d6 5d e0 20 24 e4 fc 
ff 8a 31 72 2a 47 2b 0a d3 8c ff 00 c1 d8 92 e0 
41 cf 0a d0 2a 0b d1 2b 0b d7 87 e0 40 cf 20 24 
e4 00 00 ac 7c e0 d8 ad e0 40 d6 ae e0 41 cf 20 
24 e4 ff ff a5 f6 71 53 c6 d8 c3 e0 a5 f6 71 7c 
d6 c6 e0 a5 f6 71 8f fd a2 ff ff a0 ff ff 53 b8 
73 b3 8d 1a e9 39 ee 04 61 8d 1b e9 39 ee 04 cf 
20 24 e4 00 00 ac 03 e0 66 e9 3b e0 02 64 e9 3b 
e0 02 ac af e0 a4 fd 71 d7 00 e1 61 e9 3b e0 02 
a5 fa 71 53 c1 d8 0d e1 60 e9 3b e0 02 a5 fa 71 
53 c0 d8 27 e1 ac 9e e0 d8 22 e1 40 a9 fa 71 d6 
e5 e0 63 e9 3b e0 02 a5 fa 71 55 c0 d8 f5 e0 d6 
1b e1 d6 f5 e0 d6 e5 e0 cf 20 24 e4 00 00 0e d7 
45 e1 89 ff cf 0e b7 26 b7 14 0d b7 26 b7 14 0c 
b7 26 b7 15 b7 01 b7 15 b7 02 b7 27 cf 20 24 e4 
00 00 3c 3e 0c b0 1d bb b3 e9 9f f2 04 b1 cf 20 
24 e4 00 00 3d 0c b0 b3 e9 9f f2 04 b3 0c b4 b3 
b0 bc b1 cf 20 24 e4 fe ff 8d 64 3d 0c b0 b3 e9 
39 e1 06 2b 3b 0c b4 b3 b0 bc b1 0b cf 20 24 e4 
00 00 0c d7 ad e1 0d d7 ad e1 89 32 cf 8d 63 61 
0c 1d bb b3 8d 64 3c e9 39 e1 06 b3 e9 a3 f2 04 
b3 e9 9f f2 04 cf 20 24 e4 fe ff 0d d7 d5 e1 0f 
d7 d5 e1 40 cf 0f b7 26 b7 14 0d b7 26 b7 15 b7 
03 b7 14 0f b7 26 b7 14 0e b7 26 b7 15 b7 01 b7 
14 0d b7 26 b7 14 0c b7 26 b7 15 b7 01 b7 15 b7 
Set Mapper manually
Set PRG Size
Set CHR Size
Set RAM Size

NES CART READER

CURRENT SETTINGS

MAPPER:   5
PRG SIZE: 256K
CHR SIZE: 128K
RAM SIZE: 16K

Press Button...

[+] Read iNES Rom


Saving to NES/ROM/CART/776/...
[*******************]
CRC32... 39F2CE4B -> Suikoden - Tenmei no Chikai (Japan).nes

Press Button...

I tried dumping again a few times earlier, but at that time it was recognized as 0A9725FE
I thought that the log was rewritten by mistake, but the update date of the txt file was 20230101.


OSCR HW3 V12.4

[+] Add-ons

[+] 80s Consoles

[+] NES/Famicom


Searching database
for 0A9725FE...

NES CART READER

CURRENT SETTINGS

MAPPER:   5
PRG SIZE: 256K
CHR SIZE: 128K
RAM SIZE: 8K

Press Button...

[+] Read iNES Rom


Saving to NES/ROM/SuikodenTenmein/1443/...
[*******************]
CRC32... 39F2CE4B -> Suikoden - Tenmei no Chikai (Japan).nes

Press Button...


IMG_20230414_102113
-9761c3be2976.jpg)

**Pull request merged**
